openapi: 3.1.0
x-stoplight:
  id: j388fn92qyj2u
info:
  title: Bank Feed API
  version: 2.1.0
  contact:
    email: support@codat.io
    name: Codat
  description: |-
    Bank Feed API enables your SMB users to set up bank feeds from accounts in your application to supported accounting platforms.

    A bank feed is a connection between a source bank account—in your application—and a target bank account in a supported accounting package.

    [Read more...](https://codat-docs.vercel.app/bank-feed-api/overview)
  termsOfService: 'https://www.codat.io/legals/'
servers:
  - url: 'https://api.codat.io'
    description: Codat
tags:
  - name: Bank feeds
    description: Bank feed bank accounts
paths:
  '/companies/{companyId}/connections/{connectionId}/connectionInfo/bankFeedAccounts/{bankAccountId}':
    patch:
      tags:
        - Bank feeds
      summary: Update BankFeed BankAccount
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: connectionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - $ref: '#/components/parameters/bankAccountId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankFeedBankAccount'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankFeedBankAccount'
      security:
        - API_Key: []
      description: Update a single BankFeed BankAccount for a single data source connected to a single company.
      operationId: get-bank-feed
  '/companies/{companyId}/connections/{connectionId}/connectionInfo/bankFeedAccounts':
    get:
      tags:
        - Bank feeds
      summary: List BankFeed BankAccounts
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: connectionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankFeedBankAccount'
      security:
        - API_Key: []
      description: Get BankFeed BankAccounts for a single data source connected to a single company.
      operationId: get-bank-feeds
    put:
      tags:
        - Bank feeds
      summary: Update BankFeed BankAccounts
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: connectionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BankFeedBankAccount'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankFeedBankAccount'
      security:
        - API_Key: []
      description: Put BankFeed BankAccounts for a single data source connected to a single company.
      operationId: put-bank-feeds
components:
  schemas:
    BankFeedBankAccount:
      title: BankFeedBankAccount
      x-stoplight:
        id: bi83u58u7g3vr
      type: object
      properties:
        id:
          type: string
          nullable: true
        accountName:
          type: string
          nullable: true
        accountType:
          type: string
          nullable: true
        accountNumber:
          type: string
          nullable: true
        sortCode:
          type: string
          nullable: true
        currency:
          type: string
          nullable: true
        balance:
          type: number
          format: double
          nullable: true
        modifiedDate:
          type: string
          format: date-time
          nullable: true
        status:
          type: string
          nullable: true
        feedStartDate:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
  parameters:
    bankAccountId:
      name: bankAccountId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 8a210b68-6988-11ed-a1eb-0242ac120002
      description: Unique identifier for an account
  securitySchemes:
    API_Key:
      type: apiKey
      description: 'The word "Basic" followed by a space and your API Key, base64 encoded, which can be found [here](https://app.codat.io/#/profile)'
      name: Your Base 64 encoded API Key
      in: header
security:
  - API_Key: []
