openapi: 3.1.0
x-stoplight:
  id: j388fn92qyj2u
info:
  title: Bank Feeds API
  version: 2.1.0
  contact:
    email: support@codat.io
    name: Codat
  description: |-
    Bank Feeds API enables your SMB users to set up bank feeds from accounts in your application to supported accounting platforms.

    A bank feed is a connection between a source bank account—in your application—and a target bank account in a supported accounting package.

    [Read more...](https://codat-docs.vercel.app/bank-feeds-api/overview)
  termsOfService: 'https://www.codat.io/legals/'
servers:
  - url: 'https://api.codat.io'
    description: Production
tags:
  - name: Bank feeds
    description: Bank feed bank accounts
paths:
  '/companies/{companyId}/connections/{connectionId}/connectionInfo/bankFeedAccounts/{bankAccountId}':
    patch:
      tags:
        - Bank feeds
      summary: Update BankFeed BankAccount
      parameters:
        - $ref: '#/paths/~1companies~1%7BcompanyId%7D~1connections~1%7BconnectionId%7D~1connectionInfo~1bankFeedAccounts/get/parameters/0'
        - $ref: '#/paths/~1companies~1%7BcompanyId%7D~1connections~1%7BconnectionId%7D~1connectionInfo~1bankFeedAccounts/get/parameters/1'
        - $ref: '#/components/parameters/bankAccountId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankFeedBankAccount'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankFeedBankAccount'
      security:
        - API_Key: []
      description: Update a single BankFeed BankAccount for a single data source connected to a single company.
      operationId: get-bank-feed
  '/companies/{companyId}/connections/{connectionId}/connectionInfo/bankFeedAccounts':
    get:
      tags:
        - Bank feeds
      summary: List BankFeed BankAccounts
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 8a210b68-6988-11ed-a1eb-0242ac120002
            description: Unique identifier for your SMB in Codat.
          x-stoplight:
            id: l1juboychi4p9
        - name: connectionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 2e9d2c44-f675-40ba-8049-353bfcb5e171
            description: Unique identifier for a company's data connection.
          x-stoplight:
            id: odjhmld3g3nmi
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankFeedBankAccount'
      security:
        - API_Key: []
      description: Get BankFeed BankAccounts for a single data source connected to a single company.
      operationId: get-bank-feeds
    put:
      tags:
        - Bank feeds
      summary: Update BankFeed BankAccounts
      parameters:
        - $ref: '#/paths/~1companies~1%7BcompanyId%7D~1connections~1%7BconnectionId%7D~1connectionInfo~1bankFeedAccounts/get/parameters/0'
        - $ref: '#/paths/~1companies~1%7BcompanyId%7D~1connections~1%7BconnectionId%7D~1connectionInfo~1bankFeedAccounts/get/parameters/1'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BankFeedBankAccount'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankFeedBankAccount'
      security:
        - API_Key: []
      description: Put BankFeed BankAccounts for a single data source connected to a single company.
      operationId: put-bank-feeds
components:
  schemas:
    BankFeedBankAccount:
      title: BankFeedBankAccount
      x-stoplight:
        id: bi83u58u7g3vr
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          description: Unique ID for the BankFeedBankAccount
        accountName:
          type: string
          nullable: true
          description: The bank account name
        accountType:
          type: string
          enum:
            - Unknown
            - Credit
            - Debit
          nullable: true
          description: The type of bank account e.g. Credit
        accountNumber:
          type: string
          nullable: true
          description: The account number
        sortCode:
          type: string
          nullable: true
          description: The sort code
        currency:
          type: string
          nullable: true
          description: The currency e.g. USD
        balance:
          type: number
          format: double
          nullable: true
          description: The latest balance for the bank account
        modifiedDate:
          type: string
          format: date-time
          nullable: true
          description: The last date the bank account was modified
        status:
          type: string
          nullable: true
          description: null
        feedStartDate:
          type: string
          format: date-time
          nullable: true
          description: null
      required:
        - id
      description: The target bank account in a supported accounting package for ingestion into a bank feed.
      examples:
        - id: acc-002
          accountName: account-081
          sortCode: '123456'
          accountType: Credit
          accountNumber: '12345670'
          currency: GBP
          balance: 99.99
          modifiedDate: '2023-01-09T14:14:14.1057478Z'
          status: pending
        - id: acc-003
          accountName: account-095
          sortCode: '123456'
          accountType: Credit
          accountNumber: '12345671'
          currency: USD
          balance: 0
          modifiedDate: '2023-01-09T14:14:14.1057478Z'
          status: pending
  parameters:
    bankAccountId:
      name: bankAccountId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 8a210b68-6988-11ed-a1eb-0242ac120002
      description: Unique identifier for an account
  securitySchemes:
    API_Key:
      type: apiKey
      description: 'The word "Basic" followed by a space and your API Key, base64 encoded, which can be found [here](https://app.codat.io/#/profile)'
      name: Your Base 64 encoded API Key
      in: header
security:
  - API_Key: []
